services:
  application:
    container_name: backgu-api
    image: 730335493019.dkr.ecr.ap-northeast-2.amazonaws.com/backgu-repository:api
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "10.0.5.59:9092"
