services:
  application:
    container_name: backgu-batch
    image: 730335493019.dkr.ecr.ap-northeast-2.amazonaws.com/backgu-repository:batch
    network_mode: "host"
    restart: on-failure
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "10.0.5.59:9092"
