

spring:
  application:
    name: a-maker

  datasource:
    url: jdbc:mysql://localhost:3306/amaker
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create