spring:
  application:
    name: a-maker

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  kafka:
    bootstrap-servers: [ "localhost:9092" ]

  data:
    redis:
      host: localhost
      port: 6379
