spring:
  application:
    name: a-maker

  batch-datasource:
    url: jdbc:mysql://localhost:3306/amaker_batch?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  domain-datasource:
    url: jdbc:mysql://localhost:3306/amaker?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  kafka:
    bootstrap-servers: [ "localhost:9092" ]

  data:
    redis:
      host: localhost
      port: 6379

